#!/bin/bash
cd dots

# copy .Xresources
cp .Xresources ~/

# copy .zshrc
cp .zshrc ~/

# copy .vimrc
cp .vimrc ~/
cp -r .vim ~/

#copy pipelines and scripts to ~/.bin
mkdir -p ~/.bin
cp .bin/* ~/.bin/

#copy toys
mkdir -p ~/.toys
cp .toys/* ~/.toys/

#copy al-include.cfg to /usr/lib/archlabs/common
sudo mkdir -p /usr/lib/archlabs/common
sudo cp .bin/al-include.cfg /usr/lib/archlabs/common/
sudo chown root:root /usr/lib/archlabs/common/al-include.cfg

#copy wallpapers
mkdir -p ~/wallpapers
cp wallpapers/* ~/wallpapers/

# copy .ncmpcpp
cp -r .ncmpcpp ~/

#copy .config
cp -r .config  ~/

#copy openbox configuration
#mkdir -p ~/.config/openbox
#mkdir -p ~/.config/obmenu-generator
#cp .config/openbox/* ~/.config/openbox/
#cp .config/obmenu-generator/* ~/.config/obmenu-generator/

#copy oblogout configuration 
#mkdir -p /.config/oblogout
#cp .config/oblogout/* /.config/oblogout/

#copy compton configuration
#mkdir -p ~/.config/compton
#cp .config/compton/* ~/.config/compton/

#copy tint2 configuration
#mkdir -p ~/.config/tint2
#cp .config/tint2/* ~/.config/tint2/

#copy pcmanfm configuration
#mkdir -p ~/.config/pcmanfm/default
#cp .config/pcmanfm/default/* ~/.config/pcmanfm/default/

#copy neofetch configuration
#mkdir -p ~/.config/neofetch
#cp ./config/neofetch/* ~/.config/neofetch/

# copy .profile

#copy nitrogen configuration
#mkdir -p ~/.config/nitrogen
#cp .config/nitrogen/* ~/.config/nitrogen/

#copy termite configuration
#mkdir -p ~/.config/termite
#cp .config/termite/* ~/.config/termite/

#copy ranger configuration
#mkdir -p ~/.config/ranger
#cp .config/ranger/* ~/.config/ranger/

# mpdsonglisten service
#mkdir -p /.config/systemd/user/
#cp .config/systemd/user/mpdsonglisten.service ~/.config/systemd/user/

sudo cp .bin/mpdsonglisten /usr/bin/

# enable mpdsonglisten user service
systemctl --user enable mpdsonglisten
systemctl --user start mpdsonglisten

# install and enable rtorrent
sudo pacman -S --noconfirm --needed screen rtorrent

mkdir -p ~/rtorrent
cp .rtorrent.rc ~/

systemctl --user enable rtorrent
systemctl --user start rtorrent

mkdir -p ~/.local/share/applications/
cp .local/share/applications/rtorrent-magnet.desktop ~/.local/share/applications/
xdg-mime default rtorrent-magnet.desktop x-scheme-handler/magnet

#copy vivaldi conf - check for updates at https://github.com/Tiamarth/Arc-for-Vivaldi
sudo cp vivaldi/*.css /opt/vivaldi/resources/vivaldi/style
sudo cp -R vivaldi/arc /opt/vivaldi/resources/vivaldi/style
sudo cp vivaldi/browser.html /opt/vivaldi/resources/vivaldi/

echo "!!! You need to modify the Vivaldi Theme by hand !!!"
echo "Check values at https://github.com/Tiamarth/Arc-for-Vivaldi"
echo "Add arc.css to browser.html"

echo "Reconfigure openbox and generate new menu"
