#!/usr/bin/env bash

red='\E[1;31m'
green='\E[1;32m'
reg='\E[0m'

while ! [[ $nvd ]]; do
    clear
    printf "\n  Which driver to install?
    \n  1 - Attempt to match card against a list of known cards
      and install the correct driver (pre geforce 4xx series cards)
    \n  2 - Install the most recent drivers
      Recommended option (geforce 4/5/6/7/9/10xx series cards)
    \n  3 - Same as above but also installs and sets up bumblebee.
      This is for optimus laptops, with both nvidia & integrated GPUs
    \n  4 - Revert to the open source nouveau drivers
    \n  0 - Exit installation, making no changes\n
    \n  See: ${green}http://www.nvidia.com/Download/index.aspx${reg} for more info\n\n\n: "
    read -r nvd

    clear
    case "$nvd" in
        1) sudo install-nvidia    ;;
        2) sudo install-nvidia -f ;;
        3) sudo install-nvidia -b ;;
        4) sudo install-nvidia -n ;;
        0) exit 0 ;;
        *) echo -e "${red}Invalid option${reg}" ; sleep 1 ; nvd=""
    esac
done

if grep -q "[12]" <<< "$nvd"; then
    if ! pacman -Qsq xorg-server-devel &>/dev/null; then
        sudo pacman -S xorg-server-devel --needed --noconfirm
    fi
    sudo nvidia-xconfig
elif grep -q "4" <<< "$nvd"; then
    if pacman -Qsq xorg-server-devel &>/dev/null; then
        sudo pacman -S xorg-server-devel --needed --noconfirm
    fi
fi
