directory: ~/Music
library: ~/.beets/musiclibrary.blb

import:
  move: no
  copy: yes

plugins: discogs copyartifacts

paths:
  #default: %upper{$albumartist}/$year - $albumartist - $album {${label}%ifdef{catalognum, - }$catalognum}/$track $title
  default: %upper{$albumartist}/$year - $albumartist - $album {${label}%ifdef{catalognum, - }$catalognum$}/$track - $title



#copyartifacts:
#  extensions: .*